require "rails_helper"

RSpec.describe ProfileToken do
  let(:sample_payload) do
    {
      avoid_ingredient_ids: %w[ing-dairy ing-egg],
      avoid_tag_ids:        %w[tag-contains-dairy],
      strictness:           "balanced"
    }
  end

  describe "encode + decode round-trip" do
    it "preserves every field" do
      token   = described_class.encode(**sample_payload)
      decoded = described_class.decode(token)
      expect(decoded.avoid_ingredient_ids).to eq(sample_payload[:avoid_ingredient_ids])
      expect(decoded.avoid_tag_ids).to        eq(sample_payload[:avoid_tag_ids])
      expect(decoded.strictness).to           eq(sample_payload[:strictness])
    end

    it "produces URL-safe characters only (no +, /, or =)" do
      token = described_class.encode(**sample_payload)
      expect(token).to match(/\A[A-Za-z0-9_-]+\z/)
    end

    it "round-trips empty avoid lists" do
      token = described_class.encode(avoid_ingredient_ids: [], avoid_tag_ids: [], strictness: "relaxed")
      decoded = described_class.decode(token)
      expect(decoded.avoid_ingredient_ids).to eq([])
      expect(decoded.avoid_tag_ids).to eq([])
      expect(decoded.strictness).to eq("relaxed")
    end
  end

  describe "TS ↔ Ruby parity" do
    # Tokens generated by the TS implementation at
    # packages/filter-engine/src/profile-token.ts must decode to the
    # same payload here. These fixtures are the byte-for-byte output
    # of `encodeProfileToken({ avoid_ingredient_ids, avoid_tag_ids,
    # strictness })` for the two payloads below.
    # Fixed exp (2100-01-01 UTC) so the bytes are deterministic across
    # languages. Produced by encodeProfileToken(sample, { expiresAt:
    # 4102444800 }) in the TS module.
    FIXED_EXP = 4_102_444_800
    TS_TOKEN  = "eyJ2IjoyLCJhaSI6WyJpbmctZGFpcnkiLCJpbmctZWdnIl0sImF0IjpbInRhZy1jb250YWlucy1kYWlyeSJdLCJzIjoiYmFsYW5jZWQiLCJleHAiOjQxMDI0NDQ4MDB9".freeze

    it "decodes a token produced by the TS encoder (sample payload)" do
      decoded = described_class.decode(TS_TOKEN)
      expect(decoded.avoid_ingredient_ids).to eq(%w[ing-dairy ing-egg])
      expect(decoded.avoid_tag_ids).to        eq(%w[tag-contains-dairy])
      expect(decoded.strictness).to           eq("balanced")
    end

    it "encodes the same payload to the same string the TS encoder produces" do
      ours = described_class.encode(**sample_payload, expires_at: FIXED_EXP)
      expect(ours).to eq(TS_TOKEN)
    end
  end

  describe "expiry (legal E6)" do
    it "round-trips a token with a future expiry" do
      token = described_class.encode(**sample_payload, expires_at: Time.now.to_i + 3600)
      expect(described_class.decode(token).strictness).to eq("balanced")
    end

    it "rejects an expired token" do
      token = described_class.encode(**sample_payload, expires_at: Time.now.to_i - 1)
      expect { described_class.decode(token) }
        .to raise_error(ProfileToken::InvalidTokenError, /expired/)
    end

    it "rejects a token whose exp is missing or non-numeric" do
      bad = Base64.urlsafe_encode64(
        JSON.generate(v: 2, ai: [], at: [], s: "balanced"), padding: false
      )
      expect { described_class.decode(bad) }
        .to raise_error(ProfileToken::InvalidTokenError, /exp must be a number/)
    end
  end

  describe "decode error cases" do
    it "rejects empty strings" do
      expect { described_class.decode("") }.to raise_error(ProfileToken::InvalidTokenError, /empty/)
    end

    it "rejects non-base64url garbage" do
      expect { described_class.decode("not!base64@@@") }
        .to raise_error(ProfileToken::InvalidTokenError, /not base64url/)
    end

    it "rejects unsupported schema versions" do
      future = Base64.urlsafe_encode64(JSON.generate(v: 99, ai: [], at: [], s: "balanced"), padding: false)
      expect { described_class.decode(future) }
        .to raise_error(ProfileToken::InvalidTokenError, /unsupported version/)
    end

    it "rejects invalid strictness values" do
      bad = Base64.urlsafe_encode64(
        JSON.generate(v: 2, ai: [], at: [], s: "YOLO", exp: 4_102_444_800), padding: false
      )
      expect { described_class.decode(bad) }
        .to raise_error(ProfileToken::InvalidTokenError, /s must be one of/)
    end

    it "rejects non-string ids" do
      bad = Base64.urlsafe_encode64(
        JSON.generate(v: 2, ai: [42], at: [], s: "balanced", exp: 4_102_444_800), padding: false
      )
      expect { described_class.decode(bad) }
        .to raise_error(ProfileToken::InvalidTokenError, /ai must be an array of strings/)
    end
  end
end
