/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email + password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        user: {
                            /** Format: email */
                            email: string;
                            password: string;
                        };
                    };
                };
            };
            responses: {
                /** @description JWT issued in Authorization header */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description wrong password or unknown email */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Log out — rotates the user's `jti` so the JWT is dead immediately */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description Bearer <jwt> from signup or login */
                    Authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh — mints a new JWT and rotates `jti` so the previous one dies */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Bearer <jwt> currently in use */
                    Authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description fresh JWT in Authorization header */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign up a new user (email + password) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        user: {
                            /** Format: email */
                            email: string;
                            password: string;
                            password_confirmation: string;
                            handle: string;
                            display_name?: string | null;
                        };
                    };
                };
            };
            responses: {
                /** @description user created — JWT in Authorization header */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description validation failed (e.g. duplicate email or invalid handle) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrors"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the caller's dietary profile */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Bearer <jwt> */
                    Authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the profile payload */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfilePayload"];
                    };
                };
                /** @description missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the caller's dietary profile */
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description Bearer <jwt> */
                    Authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        avoid_ingredient_ids?: string[];
                        avoid_tag_ids?: string[];
                        prefer_tag_ids?: string[];
                        /** @enum {string} */
                        strictness?: "relaxed" | "balanced" | "strict";
                        dietary_profile_slug?: string;
                    };
                };
            };
            responses: {
                /** @description updated profile payload */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfilePayload"];
                    };
                };
                /** @description unknown dietary_profile_slug */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description invalid strictness or other validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrors"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/restaurants/{restaurant_id}/items": {
        parameters: {
            query?: {
                /** @description DietaryProfile slug whose avoid lists to apply */
                profile?: string;
                /** @description Override the strictness from profile/user */
                strictness?: "relaxed" | "balanced" | "strict";
            };
            header?: never;
            path: {
                /**
                 * Format: uuid
                 * @description Published restaurant id
                 */
                restaurant_id: string;
            };
            cookie?: never;
        };
        /** List published items at this restaurant with per-item filter status */
        get: {
            parameters: {
                query?: {
                    /** @description DietaryProfile slug whose avoid lists to apply */
                    profile?: string;
                    /** @description Override the strictness from profile/user */
                    strictness?: "relaxed" | "balanced" | "strict";
                };
                header?: never;
                path: {
                    /**
                     * Format: uuid
                     * @description Published restaurant id
                     */
                    restaurant_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description items + per-item status (visible | hidden) + reasons[] */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            restaurant_id: string;
                            filter: {
                                /** @enum {string} */
                                source?: "none" | "preset" | "user_profile";
                                preset_slug?: string | null;
                                /** @enum {string} */
                                strictness?: "relaxed" | "balanced" | "strict";
                                avoid_ingredient_ids?: string[];
                                avoid_tag_ids?: string[];
                            };
                            items: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                restaurant_id: string;
                                name: string;
                                description?: string | null;
                                /** @enum {string} */
                                confidence: "confirmed" | "suggested" | "inferred";
                                popularity?: number;
                                ingredient_ids: string[];
                                tag_ids: string[];
                                /** @enum {string} */
                                status: "visible" | "hidden";
                                reasons: {
                                    /** @enum {string} */
                                    kind: "avoid_ingredient" | "avoid_tag" | "unconfirmed_strict";
                                    /** Format: uuid */
                                    ingredient_id?: string;
                                    /** Format: uuid */
                                    tag_id?: string;
                                    /** @enum {string} */
                                    confidence?: "confirmed" | "suggested" | "inferred";
                                }[];
                            }[];
                        };
                    };
                };
                /** @description restaurant not found, not published, or unknown profile slug */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error?: string;
        };
        ValidationErrors: {
            errors?: {
                [key: string]: string[];
            };
        };
        UserPayload: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            handle: string;
            display_name?: string | null;
            /** @enum {string|null} */
            provider?: "google_oauth2" | "apple" | null;
        };
        AuthResponse: {
            user: components["schemas"]["UserPayload"];
        };
        ProfilePayload: {
            avoid_ingredient_ids: string[];
            avoid_tag_ids: string[];
            prefer_tag_ids: string[];
            /** @enum {string} */
            strictness: "relaxed" | "balanced" | "strict";
            primary_dietary_profile: {
                /** Format: uuid */
                id?: string;
                slug?: string;
                name?: string;
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
