/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/account/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export the caller's personal data as a JSON archive (legal E3) */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Bearer <jwt> */
                    Authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the personal-data archive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            exported_at: string;
                            account: {
                                /** Format: uuid */
                                id: string;
                                email: string;
                                handle: string;
                                display_name: string | null;
                                provider: string | null;
                                /** Format: date-time */
                                created_at: string;
                            };
                            profile: Record<string, never> | null;
                            reviews: Record<string, never>[];
                            suggestions: Record<string, never>[];
                            restaurant_visits: Record<string, never>[];
                        };
                    };
                };
                /** @description missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ops dashboard: ingestion cost metrics, community spend, queue counts */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Bearer <jwt> for a user with is_admin */
                    Authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description metrics buckets + community counters + queue counts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            target_cents_per_item: number;
                            periods: {
                                today: {
                                    label: string;
                                    run_count: number;
                                    item_count: number;
                                    total_cost_cents: number;
                                    cost_per_item_cents: number;
                                    avg_latency_ms?: number | null;
                                    p95_latency_ms?: number | null;
                                    cache_hit_rate: number;
                                };
                                last_7_days: {
                                    label: string;
                                    run_count: number;
                                    item_count: number;
                                    total_cost_cents: number;
                                    cost_per_item_cents: number;
                                    avg_latency_ms?: number | null;
                                    p95_latency_ms?: number | null;
                                    cache_hit_rate: number;
                                };
                                last_30_days: {
                                    label: string;
                                    run_count: number;
                                    item_count: number;
                                    total_cost_cents: number;
                                    cost_per_item_cents: number;
                                    avg_latency_ms?: number | null;
                                    p95_latency_ms?: number | null;
                                    cache_hit_rate: number;
                                };
                            };
                            community: {
                                runs_today: number;
                                spend_today_cents: number;
                                ceiling_cents: number;
                            };
                            queues: {
                                flagged_reviews: number;
                                pending_suggestions: number;
                                community_published_restaurants: number;
                                staged_runs: number;
                            };
                        };
                    };
                };
                /** @description missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description authenticated but not an admin */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ingestion_runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cross-user ingestion runs queue */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by run status (unknown values are ignored) */
                    status?: "queued" | "extracting" | "resolving" | "staged" | "published" | "failed";
                    /** @description Only runs scanned by non-admin users */
                    community?: "true";
                    /** @description Filter to one restaurant */
                    restaurant_id?: string;
                    /** @description Page size (default 25, max 100) */
                    limit?: number;
                    offset?: number;
                };
                header: {
                    /** @description Bearer <jwt> for a user with is_admin */
                    Authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description runs newest-first + pagination */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            runs: {
                                /** Format: uuid */
                                id: string;
                                /** @enum {string} */
                                status: "queued" | "extracting" | "resolving" | "staged" | "published" | "failed";
                                enrichment_status?: string | null;
                                input_kind?: string;
                                failure_message?: string | null;
                                api_cost_cents?: number | null;
                                /** Format: date-time */
                                created_at?: string;
                                user?: {
                                    /** Format: uuid */
                                    id?: string;
                                    handle?: string;
                                    email?: string;
                                    is_admin?: boolean;
                                } | null;
                                restaurant?: {
                                    /** Format: uuid */
                                    id?: string;
                                    name?: string;
                                    slug?: string;
                                    /** @enum {string} */
                                    status?: "draft" | "published" | "closed";
                                } | null;
                                decision_counts: {
                                    pending: number;
                                    accepted: number;
                                    rejected: number;
                                    edited: number;
                                };
                            }[];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
                /** @description authenticated but not an admin */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ingestion_runs/{id}/re_extract": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** Format: uuid */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rewind a run to :queued and re-fire extraction */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Bearer <jwt> for a user with is_admin */
                    Authorization: string;
                };
                path: {
                    /** Format: uuid */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description run rewound and ExtractMenuJob enqueued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** @enum {string} */
                            status: "queued";
                        };
                    };
                };
                /** @description run is already published — its items are live */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/restaurants/{id}/confirm_community": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** Format: uuid */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Graduate community data to strict-mode visibility
         * @description Flips the restaurant's suggested human-sourced joins to confirmed, then graduates items whose every association is confirmed. Idempotent.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Bearer <jwt> for a user with is_admin */
                    Authorization: string;
                };
                path: {
                    /** Format: uuid */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description counts of rows flipped by this call */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            restaurant_id: string;
                            confirmed: {
                                items: number;
                                ingredients: number;
                                tags: number;
                            };
                        };
                    };
                };
                /** @description not an admin, or unknown restaurant */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email + password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        user: {
                            /** Format: email */
                            email: string;
                            password: string;
                        };
                    };
                };
            };
            responses: {
                /** @description JWT issued in Authorization header */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description wrong password or unknown email */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Log out — rotates the user's `jti` so the JWT is dead immediately */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description Bearer <jwt> from signup or login */
                    Authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh — mints a new JWT and rotates `jti` so the previous one dies */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Bearer <jwt> currently in use */
                    Authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description fresh JWT in Authorization header */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign up a new user (email + password) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        user: {
                            /** Format: email */
                            email: string;
                            password: string;
                            password_confirmation: string;
                            handle: string;
                            display_name?: string | null;
                            age_confirmation: boolean;
                            terms_acceptance: boolean;
                        };
                    };
                };
            };
            responses: {
                /** @description user created — JWT in Authorization header */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description terms not accepted — clickwrap gate */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrors"];
                    };
                };
            };
        };
        /** Delete the caller's account (legal remediation E2) */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description Bearer <jwt> */
                    Authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description account deleted — personal data removed, menu-graph attribution nulled */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion_runs/{ingestion_run_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** Format: uuid */
                ingestion_run_id: string;
            };
            cookie?: never;
        };
        /** List a run's staged items (owner or admin) */
        get: {
            parameters: {
                query?: never;
                header: {
                    Authorization: string;
                };
                path: {
                    /** Format: uuid */
                    ingestion_run_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description items in position order */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["IngestionItemPayload"][];
                        };
                    };
                };
                /** @description not the run's creator and not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion_runs/{ingestion_run_id}/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** Format: uuid */
                ingestion_run_id: string;
                /** Format: uuid */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Decide a staged item: accept / edit / reject / undo */
        patch: {
            parameters: {
                query?: never;
                header: {
                    Authorization: string;
                };
                path: {
                    /** Format: uuid */
                    ingestion_run_id: string;
                    /** Format: uuid */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        decision: "accepted" | "edited" | "rejected" | "pending";
                        name?: string;
                        description?: string;
                        ingredients_payload?: {
                            [key: string]: unknown;
                        }[];
                        tags_payload?: {
                            [key: string]: unknown;
                        }[];
                        addons_payload?: {
                            [key: string]: unknown;
                        }[];
                        unresolved_ingredients?: string[];
                        unresolved_tags?: string[];
                    };
                };
            };
            responses: {
                /** @description the updated item */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngestionItemPayload"];
                    };
                };
                /** @description unknown decision value */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                            allowed?: string[];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/ingestion_runs/{ingestion_run_id}/items/accept_all": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** Format: uuid */
                ingestion_run_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk-accept every still-pending item */
        post: {
            parameters: {
                query?: never;
                header: {
                    Authorization: string;
                };
                path: {
                    /** Format: uuid */
                    ingestion_run_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description all items after the bulk accept */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["IngestionItemPayload"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion_runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** Format: uuid */
                id: string;
            };
            cookie?: never;
        };
        /** Read a run's status + counters (owner or admin) */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Bearer <jwt> — the run's creator or an admin */
                    Authorization: string;
                };
                path: {
                    /** Format: uuid */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the run */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngestionRunPayload"];
                    };
                };
                /** @description someone else's run (deliberately not 403), or unknown id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the caller's own identity payload */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Bearer <jwt> */
                    Authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the caller's user payload (incl. is_admin) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the caller's dietary profile */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Bearer <jwt> */
                    Authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the profile payload */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfilePayload"];
                    };
                };
                /** @description missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the caller's dietary profile */
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description Bearer <jwt> */
                    Authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        avoid_ingredient_ids?: string[];
                        avoid_tag_ids?: string[];
                        prefer_tag_ids?: string[];
                        liked_ingredient_ids?: string[];
                        liked_tag_ids?: string[];
                        disliked_ingredient_ids?: string[];
                        disliked_tag_ids?: string[];
                        /** @enum {string} */
                        strictness?: "relaxed" | "balanced" | "strict";
                        dietary_profile_slug?: string;
                        /** @description When true, server-stamps disclaimer_acknowledged_at (first acknowledgment only). Sent by onboarding. */
                        acknowledge_disclaimer?: boolean;
                    };
                };
            };
            responses: {
                /** @description acknowledging the allergen disclaimer stamps a timestamp */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfilePayload"];
                    };
                };
                /** @description unknown dietary_profile_slug */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description invalid strictness or other validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrors"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/restaurants/{restaurant_id}/items": {
        parameters: {
            query?: {
                /** @description DietaryProfile slug whose avoid lists to apply */
                profile?: string;
                /** @description Override the strictness from profile/user */
                strictness?: "relaxed" | "balanced" | "strict";
            };
            header?: never;
            path: {
                /**
                 * Format: uuid
                 * @description Published restaurant id
                 */
                restaurant_id: string;
            };
            cookie?: never;
        };
        /** List published items at this restaurant with per-item filter status */
        get: {
            parameters: {
                query?: {
                    /** @description DietaryProfile slug whose avoid lists to apply */
                    profile?: string;
                    /** @description Override the strictness from profile/user */
                    strictness?: "relaxed" | "balanced" | "strict";
                };
                header?: never;
                path: {
                    /**
                     * Format: uuid
                     * @description Published restaurant id
                     */
                    restaurant_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description items + per-item status (visible | hidden) + reasons[] */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            restaurant_id: string;
                            filter: {
                                /** @enum {string} */
                                source?: "none" | "preset" | "user_profile";
                                preset_slug?: string | null;
                                /** @enum {string} */
                                strictness?: "relaxed" | "balanced" | "strict";
                                avoid_ingredient_ids?: string[];
                                avoid_tag_ids?: string[];
                            };
                            items: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                restaurant_id: string;
                                name: string;
                                description?: string | null;
                                /** @enum {string} */
                                confidence: "confirmed" | "suggested" | "inferred";
                                popularity?: number;
                                ingredient_ids: string[];
                                tag_ids: string[];
                                /** @enum {string} */
                                status: "visible" | "hidden";
                                reasons: {
                                    /** @enum {string} */
                                    kind: "avoid_ingredient" | "avoid_tag" | "unconfirmed_strict";
                                    /** Format: uuid */
                                    ingredient_id?: string;
                                    ingredient_name?: string | null;
                                    ingredient_family?: string | null;
                                    /** Format: uuid */
                                    tag_id?: string;
                                    tag_name?: string | null;
                                    tag_family?: string | null;
                                    /** @enum {string} */
                                    confidence?: "confirmed" | "suggested" | "inferred";
                                }[];
                                taste_score?: number | null;
                                taste_reasons?: {
                                    /** @enum {string} */
                                    kind: "liked_tag" | "liked_ingredient";
                                    /** Format: uuid */
                                    tag_id?: string;
                                    tag_name?: string | null;
                                    /** Format: uuid */
                                    ingredient_id?: string;
                                    ingredient_name?: string | null;
                                }[];
                            }[];
                        };
                    };
                };
                /** @description restaurant not found, not published, or unknown profile slug */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error?: string;
        };
        Pagination: {
            total: number;
            limit: number;
            offset: number;
        };
        IngestionItemPayload: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ingestion_run_id: string;
            /** Format: uuid */
            item_id?: string | null;
            position?: number | null;
            name: string;
            description?: string | null;
            section_name?: string | null;
            /** @enum {string} */
            decision: "pending" | "accepted" | "rejected" | "edited";
            /** Format: date-time */
            decided_at?: string | null;
            ingredients_payload?: {
                [key: string]: unknown;
            }[];
            tags_payload?: {
                [key: string]: unknown;
            }[];
            prices_payload?: {
                [key: string]: unknown;
            }[];
            addons_payload?: {
                [key: string]: unknown;
            }[];
            unresolved_ingredients?: string[];
            unresolved_tags?: string[];
            match?: {
                /** Format: uuid */
                item_id?: string;
                score?: number | null;
                existing?: {
                    name?: string;
                    description?: string | null;
                    prices?: {
                        [key: string]: unknown;
                    }[];
                };
                diff?: {
                    [key: string]: unknown;
                };
                no_changes?: boolean;
            } | null;
        };
        IngestionRunPayload: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "queued" | "extracting" | "resolving" | "staged" | "published" | "failed";
            /** @enum {string|null} */
            enrichment_status?: "pending" | "completed" | "failed" | null;
            /** @enum {string} */
            input_kind?: "photo" | "url" | "pdf" | "text";
            /** Format: uuid */
            restaurant_id: string;
            state_history?: {
                [key: string]: unknown;
            };
            failure_message?: string | null;
            api_cost_cents?: number | null;
            latency_ms?: number | null;
            input_count?: number;
            ingestion_items_count?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ValidationErrors: {
            errors?: {
                [key: string]: string[];
            };
        };
        UserPayload: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            handle: string;
            display_name?: string | null;
            is_admin: boolean;
            /** @enum {string|null} */
            provider?: "google_oauth2" | "apple" | null;
        };
        AuthResponse: {
            user: components["schemas"]["UserPayload"];
        };
        IngredientRef: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
        };
        TagRef: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            /** @enum {string} */
            family: "diet" | "allergen" | "cuisine" | "prep" | "flavor";
        };
        ProfilePayload: {
            avoid_ingredient_ids: string[];
            avoid_tag_ids: string[];
            prefer_tag_ids: string[];
            liked_ingredient_ids: string[];
            liked_tag_ids: string[];
            disliked_ingredient_ids: string[];
            disliked_tag_ids: string[];
            avoid_ingredients: components["schemas"]["IngredientRef"][];
            avoid_tags: components["schemas"]["TagRef"][];
            liked_ingredients: components["schemas"]["IngredientRef"][];
            liked_tags: components["schemas"]["TagRef"][];
            disliked_ingredients: components["schemas"]["IngredientRef"][];
            disliked_tags: components["schemas"]["TagRef"][];
            /** @enum {string} */
            strictness: "relaxed" | "balanced" | "strict";
            primary_dietary_profile: {
                /** Format: uuid */
                id?: string;
                slug?: string;
                name?: string;
            } | null;
            /** Format: date-time */
            disclaimer_acknowledged_at: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
